import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Appbar } from "./components/Appbar";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-background text-foreground` }>
        <Providers>
            <div className="sticky top-0 z-40 header-glass">
              <Appbar/>
            </div>
            <main className="mx-auto w-full max-w-[1600px] px-4 sm:px-6 lg:px-8 py-2">
              {children}
            </main>
          </Providers>
      </body>
    </html>
  );
}
